parameters:
    encryption:
        salt:               championsheepsalt
        
website:
    title:                  ChampionSheep
    name:                   <b>Champion</b>Sheep
    abreviation:            <b>C</b>SE

database:
    driver:        pdo_mysql
    dbname:        championsheep
    host:          localhost
    port:          3306
    user:          root
    password:      
    charset:       UTF8
    
email:
    sender:             no-reply@championsheep.com
    transport:
        type:           
        host:           localhost
        port:           25
        encryption:     TLS
        login:
        password: