website:
    title:                  ChampionSheep
    name:                   <b>Champion</b>Sheep
    abreviation:            <b>C</b>SE

database:
    driver:        pdo_mysql
    dbname:        championsheep
    host:          localhost
    port:          3306
    user:          root
    password:      
    charset:       UTF8