website:
    title:                  ChampionSheep
    name:                   <b>Champion</b>Sheep
    abreviation:            <b>C</b>SE

default_connection:
    database_driver:        pdo_mysql
    database_name:          championsheep
    database_host:          localhost
    database_port:          3306
    database_user:          root
    database_password:      
    database_charset:       UTF8