home:
    path:     /
    defaults:  
        _controller: CoreBundle\Controllers\DefaultController::indexAction
    methods:  [GET]
    
##Connection
login:
    path:     /login
    defaults:  
        _controller: CoreBundle\Controllers\LoginController::formAction
    methods:  [GET, POST]
    
logout:
    path:     /logout
    defaults:  
        _controller: CoreBundle\Controllers\LoginController::logoutAction
    methods:  [GET]
    
##Register
register:
    path:     /register
    defaults:  
        _controller: CoreBundle\Controllers\RegisterController::formAction
    methods:  [GET, POST]
    
register:
    path:     /register/confirm/{id}
    defaults:  
        _controller: CoreBundle\Controllers\RegisterController::confirmAction
    methods:  [GET]

tournaments:
    resource: "src/TournamentBundle/Resources/config/routing.yml"
    
teams:
    resource: "src/TeamBundle/Resources/config/routing.yml"