home:
    path:     /
    defaults:  
        _controller: CoreBundle\Controllers\DefaultController::indexAction
    methods:  [GET]
    
##Connection
login_form:
    path:     /login
    defaults:  
        _controller: CoreBundle\Controllers\LoginController::formAction
    methods:  [GET]
    
login_post:
    path:     /login
    defaults:  
        _controller: CoreBundle\Controllers\LoginController::loginAction
    methods:  [POST]
    
logout:
    path:     /logout
    defaults:  
        _controller: CoreBundle\Controllers\LoginController::logoutAction
    methods:  [GET]
    
##Register
register_form:
    path:     /register
    defaults:  
        _controller: CoreBundle\Controllers\RegisterController::formAction
    methods:  [GET]
    
register_ajax_control_email:
    path:     /register/control/email
    defaults:  
        _controller: CoreBundle\Controllers\RegisterController::checkInputEmail
    condition:    'context.getParameter("isXmlHttpRequest")'
    methods:  [POST]
    
register_post:
    path:     /register
    defaults:  
        _controller: CoreBundle\Controllers\RegisterController::registerAction
    methods:  [GET]