home:
    path:     /
    defaults:  
        _controller: CoreBundle\Controllers\DefaultController::indexAction
    methods:  [GET]
    
home2:
    path:     /jaimelepenis
    defaults:  
        _controller: CoreBundle\Controllers\DefaultController::indexAction
    methods:  [GET]